name: CASR Runner

on:
  push:

jobs:
  run-casr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: b075c19a548e7e1645f5024957cdec58e3dd577b

    - name: Install JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup CASR
      run: |
        curl -L -o casr-x86_64-unknown-linux-gnu.tar.xz https://github.com/ispras/casr/releases/latest/download/casr-x86_64-unknown-linux-gnu.tar.xz
        tar -xvf casr-x86_64-unknown-linux-gnu.tar.xz
        mv casr-x86_64-unknown-linux-gnu /tmp/casr
        chmod +x /tmp/casr/casr-java
        echo "/tmp/casr" >> $GITHUB_PATH

    - name: Run CASR on the .java file(s)
      continue-on-error: true
      run: |      
        set +e
        #!/bin/bash

        directory=$(pwd)
        
        java_files=$(find "$directory" -type f -name "*.java")
        
        # Loop through each .java file found
        for java_file in $java_files;
        do
            # Construct the command
            command="casr-java --stdout -- java $java_file"
            $command
        done
